services:
  dbserver:
    image: docker.io/library/postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=transportcolis

  dbclient:
    image: docker.io/library/postgres
    command: >
      sh -c "until psql -h dbserver -U admin -c 'SELECT 1'; do echo waiting for dbserver; sleep 2; done;
      psql -h dbserver -U admin --dbname=transportcolis"
    depends_on:
      - dbserver